services:
  license-server:
    build:
      context: ./license_portal
    environment:  # Add this environment setting
      - DJANGO_DB_HOST=mariadb
    links:
      - mariadb
    volumes:
      - ./license_portal:/app

  mariadb:
    image: 'mariadb:latest'
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: 'licenses'
      MYSQL_USER: 'licenses'
      MYSQL_PASSWORD: 'licenses'